### ISSUE TITLE
About the Dev section

### ISSUE THREAD

**Issue by igurgoze** [Christoph551/Couch-Potato-Assistant#16]

**Comment by igurgoze** [comment]
Create 3 divs for each member:
includes- their name, short introduction, link to github

**Comment by Christoph551** [comment]
Will also need the usage section that has short description of how to use the app.

**Comment by Christoph551** [comment]
Preliminary set up for this section is done. Needs additional styling.

**Comment by Christoph551** [comment]
Styled pages in a way that should suffice for now. 
Still need to implement media queries due to adjustments made to images in styles.css
